services:
  - type: web
    name: workwhiz
    env: python
    buildCommand: "./build.sh"
    startCommand: gunicorn WorkWhiz.wsgi:application
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: WorkWiz2.settings
      - key: SECRET_KEY
        value: ^=6od-@&vo4i$wukkbjcb2w-6ctob@*c8%=x$jc)#2(ug^(@@_
      - key: DEBUG
        value: False
    autoDeploy: true