# Generated by Django 5.2.12 on 2026-03-23 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='target_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='accounts.jobpost'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('reviewer', 'target_job', 'rating_type')},
        ),
    ]
